# PostgreSQL profile — override H2 defaults
spring.datasource.url=jdbc:postgresql://localhost:5432/incidentdb
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# Disable H2 console when using Postgres
spring.h2.console.enabled=false
